version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./api/dados:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    # env_file: ./db.env
  api:
    container_name: api
    build: ./api
    command: bash -c "rake db:create && rake db:migrate && rails server -b 0.0.0.0"
    ports:
      - 3000:3000
    volumes:
      - ./api:/api
    depends_on:
      - db
    links:
      - db
    # client:
  #   container_name: client
  #   build: ./client
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./client:/app
